resource_id: "development:0"
zone: public/dev
labels:
  environment: localdev
tls:
  provided:
    ca: certs/out/ca.pem
    cert: certs/out/tenantA.pem
    key: certs/out/tenantA-key.pem
ambassador:
  address: localhost:6565
ingest:
  lumberjack:
    bind: localhost:5044
  telegraf:
    json:
      bind: localhost:8094
