tls:
  provided:
    ca: certs/out/ca.pem
    cert: certs/out/tenantB.pem
    key: certs/out/tenantB-key.pem
ambassador:
  address: localhost:6565
ingest:
  lumberjack:
    bind: localhost:5045
  telegraf:
    json:
      bind: localhost:8095
