version: '3.2'

services:
  etcd:
    image: quay.io/coreos/etcd:${ETCD_VERSION:-v3.3.20}
    ports:
      - 2479:2379
    volumes:
      - etcd:/etcd-data
    environment:
      ETCDCTL_API: 3
    command: >
      /usr/local/bin/etcd
      --data-dir=/etcd-data --name node1
      --initial-advertise-peer-urls http://etcd:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://localhost:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster node1=http://etcd:2380
  mysql:
    image: mysql:${MYSQL_VERSION:-5.7}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: ${MYSQL_INITIAL_PASSWORD:-initialpw}
      MYSQL_ONETIME_PASSWORD: "true"

  zk:
    image: confluentinc/cp-zookeeper:${CP_VERSION:-4.1.2}
    environment:
      JAVA_TOOL_OPTIONS: -Xmx256m
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zk:/var/lib/zookeeper/data
  kafka:
    image: confluentinc/cp-kafka:${CP_VERSION:-4.1.2}
    environment:
      JAVA_TOOL_OPTIONS: -Xmx512m
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:9093
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # some loggers are set to TRACE by default...and they're noisy
      KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,state.change.logger=INFO
    volumes:
      - kafka:/var/lib/kafka/data
    ports:
      - 9092:9092
    depends_on:
      - zk
  vault:
    image: vault:${VAULT_VERSION:-1.3.2}
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN:-VaultRootToken}
    volumes:
      - ./setup-app-role.sh:/usr/local/bin/setup-app-role:ro
    ports:
      - 8200:8200
  kapacitor-0:
    image: kapacitor:${KAPACITOR_VERSION:-1.5.2}
    ports:
      - 9192:9092
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./kapacitor-load:/etc/kapacitor/load/:ro
      - kapacitor-0:/var/lib/kapacitor
  kapacitor-1:
    image: kapacitor:${KAPACITOR_VERSION:-1.5.2}
    ports:
      - 9193:9092
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./kapacitor-load:/etc/kapacitor/load/:ro
      - kapacitor-1:/var/lib/kapacitor

volumes:
  etcd:
  zk:
  kafka:
  mysql:
  kapacitor-0:
  kapacitor-1:
